<?php
include("db.inc.php");
define('FPDF_FONTPATH','font/');
require('fpdf.php');

$ComplexID = pebkac($_GET['cid'], 5);
$Complex = getComplexByID($ComplexID);
$OutPutType = 'I';
$startY = 35;
class PDF extends FPDF
{
	function Header()
	{
		global $startY;
		global $Complex;
		if($this->page > 1)
		{
			$this->SetFont('Arial','',10);
			$this->SetXY(190, 10);
			$this->Cell(10, 5, $this->page, 0, 0);
		}
		// $startY = 35;
		// $this->SetFont('Arial','B',12);
		// $this->SetXY(5, $startY);
		// $this->Cell(200, 10, "Memorandum of Understanding", 0, 10, 'C');
		// $startY += 8;
		// $this->SetFont('Arial', '', 8);
		// $this->SetXY(35, $startY);
		// $this->Cell(200, 10, "Estate Name: " . $Complex['complexname'], 0, 10);
	}

	function Footer()
	{
		global $Complex;
		if($this->page > 1)
		{
			$IniLogo = "images/logo 251x58.png";
			$this->Image($IniLogo, 160, 280, 30);
			$this->SetXY(15, 282);
			$this->SetTextColor(187, 187, 187);
			$this->Cell(100, 5, "Memorandum of Understanding: " . $Complex['complexname'], 0, 0);
			$this->SetTextColor(0, 0, 0);
		}
	}
}
$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage('P');
$pdf->SetFont('Arial','B',18);
$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "Memorandum of Understanding", 0, 0, 'C');
$pdf->SetFont('Arial','',14);
$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "for home fibre installation", 0, 0, 'C');
$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "and solutions provided by", 0, 0, 'C');
$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->SetFont('Arial','B',18);
$pdf->Cell(180, 6, "Company (Pty) Ltd", 0, 0, 'C');
$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->SetFont('Arial','',14);
$pdf->Cell(180, 6, "to", 0, 0, 'C');
$startY += 10;
$pdf->SetFont('Arial','B',18);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, $Complex['complexname'], 0, 0, 'C');
$IniLogo = "images/logo 658x150.png";
$startY += 50;
$pdf->Image($IniLogo, 65, $startY, 80);
$pdf->AddPage('P');
$startY = 35;
$pdf->SetFont('Arial','B',12);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 5, 'Contents', 0, 0);
$pdf->SetFont('Arial','',10);
$startY += 6;
$pdf->SetXY(20, $startY);
$pdf->Cell(160, 5, "Identification of parties.............................................................................................................................", 0, 0);
$pdf->Cell(10, 5, '3', 0, 0);
$startY += 6;
$pdf->SetXY(20, $startY);
$pdf->Cell(160, 5, "Aims and Objectives................................................................................................................................", 0, 0);
$pdf->Cell(10, 5, '3', 0, 0);
$startY += 6;
$pdf->SetXY(20, $startY);
$pdf->Cell(160, 5, "Legislative context...................................................................................................................................", 0, 0);
$pdf->Cell(10, 5, '4', 0, 0);
$startY += 6;
$pdf->SetXY(20, $startY);
$pdf->Cell(160, 5, "Joint undertakings and responsibilities....................................................................................................", 0, 0);
$pdf->Cell(10, 5, '4', 0, 0);
$startY += 6;
$pdf->SetXY(20, $startY);
$pdf->Cell(160, 5, "Terms of operation of the MOU...............................................................................................................", 0, 0);
$pdf->Cell(10, 5, '5', 0, 0);
$startY += 6;
$pdf->SetXY(20, $startY);
$pdf->Cell(160, 5, "Declaration of endorsement.....................................................................................................................", 0, 0);
$pdf->Cell(10, 5, '7', 0, 0);
$pdf->AddPage('P');
$startY = 20;
$pdf->SetFont('Arial','B',12);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "Identification of parties", 0, 0);
$pdf->SetFont('Arial','',10);
$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->Cell(160, 5, "This Memorandum of Understanding (MOU) is made and entered into, between", 0, 0);
$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->SetFont('Arial','B',12);
$pdf->Cell(160, 5, "Company (Pty) Ltd", 0, 0);
$startY += 6;
$pdf->SetXY(15, $startY);
$pdf->SetFont('Arial','',10);
$pdf->Cell(160, 5, "(Registration No. 2016/123456/07)", 0, 0);
$startY += 6;
$pdf->SetXY(15, $startY);
$pdf->Cell(160, 5, "(hereinafter referred to as 'Company')", 0, 0);
$startY += 6;
$pdf->SetXY(15, $startY);
$pdf->Cell(80, 5, "Physical Business Address: ", 0, 0);
$pdf->SetXY(100, $startY);
$pdf->Cell(70, 5, "23 Skyway Business Park,", 0, 0);
$startY += 6;
$pdf->SetXY(100, $startY);
$pdf->Cell(70, 5, "Frede Road,", 0, 0);
$startY += 6;
$pdf->SetXY(100, $startY);
$pdf->Cell(70, 5, "Randburg,", 0, 0);
$startY += 6;
$pdf->SetXY(100, $startY);
$pdf->Cell(70, 5, "2188", 0, 0);
$startY += 10;
// $pdf->SetXY(15, $startY);
// $pdf->Cell(160, 5, 'Postal Address: ', 1, 0);
// $startY += 6;
$pdf->SetXY(15, $startY);
$pdf->Cell(160, 5, "AND", 0, 0);
$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->SetFont('Arial','B',12);
$pdf->Cell(160, 5, $Complex['complexname'], 0, 0);
$pdf->SetFont('Arial','',10);
$startY += 6;
$pdf->SetXY(15, $startY);
$pdf->Cell(160, 5, "(Body Corporate/Home Owners' Association)", 0, 0);
$startY += 6;
$pdf->SetXY(15, $startY);
$pdf->Cell(160, 5, "(hereinafter referred to as 'the Body Corporate')", 0, 0);
$startY += 6;
$pdf->SetXY(15, $startY);
$pdf->Cell(80, 5, 'Physical Address:', 0, 0);

$AddrStr = $Complex['streetaddress1'] . '##' . $Complex['streetaddress2'] . '##' . $Complex['streetaddress3'] . '##' . $Complex['streetaddress4'] . '##' . $Complex['streetaddress5'];
$AddrArr = explode("##", $AddrStr);
foreach($AddrArr AS $ind => $Addr)
{
	if($Addr != '')
	{
		$pdf->SetXY(100, $startY);
		$pdf->Cell(70, 5, $Addr, 0, 0);
		$startY += 6;
	}
}
$startY += 6;
$pdf->SetFont('Arial','B',12);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "Aims and Objectives", 0, 0);
$pdf->SetFont('Arial','',10);
$startY += 6;
$pdf->SetXY(15, $startY);
$LongText = "This Memorandum of Understanding (MOU) is to be signed by both parties once the Letter of Engagement and Permission has been signed by an authorised Trustee of " . $Complex['complexname'] . " and the site survey and resident uptake survey has been completed by, and reported upon to the Trustees by the Company team.\n\n";
$LongText .= "The aim of this MOU is to explain the relationship between Company and " . $Complex['complexname'] . " and to clarify the responsibilities and requirements from each party during the installation of fibre to home in this residential complex.\n\n";
$LongText .= "Its objective is to ensure that the expectations of both parties are satisfactorily met, that each party clearly understands its roles and responsibilities, and the deadlines that are required to be met, to ensure that Company can successfully provide the fibre to home backbone and fibre connectivity services as outlined in the introductory proposal, in the proposed site plan, and within the stated timeframe. The MOU provides the framework for and environment in which the build and installation will take place and highlights the legislative context, joint undertakings and responsibilities, timelines, and terms of operation.";
$pdf->MultiCell(180, 6, $LongText, 0);
$pdf->AddPage('P');
$startY = 20;
$pdf->SetFont('Arial','B',12);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "Legislative context", 0, 0);
$pdf->SetFont('Arial','',10);
$startY += 10;
$pdf->SetXY(15, $startY);
$LongText = "This MOU is formal agreement binding on Company, its partner companies, and the Body Corporate and residents of " . $Complex['complexname'] . ", for the duration of the installation period and the two month period of exclusive service and marketing rights for fibre connectivity within the complex.";
$pdf->MultiCell(180, 6, $LongText, 0);
$startY += 28;
$pdf->SetFont('Arial','B',12);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "Joint undertakings and responsibilities", 0, 0);
$pdf->SetFont('Arial','B',10);
$startY += 10;
$pdf->SetXY(20, $startY);
$pdf->Cell(180, 6, "1.	The responsibilities and actions of each Party:", 0, 0);

$startY += 6;
$pdf->SetXY(25, $startY);
$pdf->Cell(6, 6, "(a)", 0);
$pdf->SetXY(31, $startY);
$pdf->Cell(160, 6, "Company (and its partners/contractors) hereby agree:", 0, 0);

$pdf->SetFont('Arial','',10);
$startY += 6;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "To install sufficient infrastructure that will accommodate all the residents on the fibre network on the site, at no cost to the Body Corporate or the residents";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 12;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "That the installation of any equipment on a resident's property will be at no cost to the resident. The only costs to residents occur when they sign a customer contract for connectivity services with Company. These costs are available in the introductory document but are subject to change without notice";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 18;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "That a resident is under no obligation to allow the installation of any equipment on their property while the build and installation project is in progress. Once the build and installation is complete, residents must be aware that there will be a cost for installation of fibre infrastructure into their homes";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 18;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "To obtain the necessary approvals/wayleaves from the relevant authorities in respect of the building and installation of the fibre network to be undertaken at the site, at their own cost";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 12;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "To commence with the build and installation only once an on-site survey and detailed site design has been completed and approved by the Body Corporate, and the necessary council approvals have been obtained";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 18;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "To complete the project at the earliest convenience, provided that the detailed site design is approved by the " . $Complex['complexname'] . " Trustees";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 12;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "To cover any costs associated with, and applicable to the build and installation of the fibre network";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 6;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "To ensure that the build and installation will be performed by suitably qualified contractors and/or consultants and/or sub-contractors who will be appointed by and paid by Company";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 12;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "To re-instate the site to its former condition in those areas specifically affected by the build and installation, ensuring that all trenching works and or excavations done are executed and remedied according to the agreed specifications and outcomes";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 18;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Gain the necessary permissions from each resident in order to complete the installation on his/her property at a time that suits all parties. The Body Corporate is under no obligation to arrange access to the individual homes.";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 18;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Company agrees that should any damage happen as a direct result of the installations the service provider would be responsible for the repairs";
$pdf->MultiCell(160, 6, $LongText, 0);

$pdf->AddPage('P');
$startY = 20;
$pdf->SetFont('Arial','B',10);
$pdf->SetXY(25, $startY);
$pdf->Cell(6, 6, "(b)", 0);
$pdf->SetXY(31, $startY);
$pdf->Cell(160, 6, "The Trustees of " . $Complex['complexname'] . ", hereby agree:", 0, 0);
$pdf->SetFont('Arial','',10);
$startY += 6;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "To grant Company (its authorised partners/contractors) access to the site to commence with the necessary surveys, preparation works, build and installation of the fibre network, and marketing of services (in accordance with the agreed upon marketing plan)";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 18;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "That the fibre infrastructure and related equipment is and will remain under the ownership of Company (or its partners/contractors)";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 12;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "That all Company deployed equipment and fibre reticulation within the Body Corporate's property from an aggregation point to the end customer will be managed, supported and configured by Company (or its partners/ contractors). In order to ensure the infrastructure is not compromised after the project is complete, Company (or its partners/contractors) will be the only company allowed to install termination points on the site";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 30;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "To provide space where possible for the storage of Company equipment during the build and installation period (if necessary)";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 12;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Not to make any warranties or representations of whatsoever nature, with regards to Company (or its partners/contractors)";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 12;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Not to bind Company (or its partners/contractors) in any way whatsoever outside the scope of this MOU";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 6;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "To acknowledge that any and all of the trademarks, trade names, copyrights, patents and other intellectual property rights used or embodied in, or connected to Company (or its partners/contractors) are and shall the property of Company (or its partners/contractors). Nothing contained in this Agreement shall be construed so as to confer on the Body Corporate any copyright or other intellectual property rights";
$pdf->MultiCell(160, 6, $LongText, 0);


$startY += 30;
$pdf->SetFont('Arial','B',10);
$pdf->SetXY(25, $startY);
$pdf->Cell(6, 6, "(c)", 0);
$pdf->SetXY(31, $startY);
$pdf->MultiCell(160, 6, "Timing, including relevant timelines, milestones and agreed frequency of cooperative activities: ", 0);
$pdf->SetFont('Arial','',10);
$startY += 12;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "These will be clearly stipulated in an annexure to this MOU which will be attached once the official go-ahead is given via the signing of the MOU";
$pdf->MultiCell(160, 6, $LongText, 0);

$startY += 18;
$pdf->SetFont('Arial','B',10);
$pdf->SetXY(25, $startY);
$pdf->Cell(6, 6, "(d)", 0);
$pdf->SetXY(31, $startY);
$pdf->MultiCell(170, 6, "Protocols for communicating between the Parties:", 0);
$pdf->SetFont('Arial','',10);
$startY += 6;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "The names of relevant Company representatives, their roles and responsibilities and those of the representatives of " . $Complex['complexname'] . " body corporate will be noted and attached as an annexure to this MOU once the official go-ahead is given";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 24;
$pdf->SetFont('Arial','B',12);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "Terms of operation of the MOU", 0, 0);
$pdf->SetFont('Arial','',10);
$startY += 10;
$pdf->SetXY(20, $startY);
$pdf->Cell(180, 6, "The MOU will be administered, in the following manner:", 0, 0);
$startY += 6;
$pdf->SetFont('Arial','B',10);
$pdf->SetXY(25, $startY);
$pdf->Cell(6, 6, "(a)", 0);
$pdf->SetXY(31, $startY);
$pdf->MultiCell(160, 6, "Term/duration of the MOU:", 0);
$pdf->SetFont('Arial','',10);
$startY += 6;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "This MOU is comes into effect on the date of signing. Notwithstanding the ownership of the infrastructure, and the related stipulations above regarding the installation of further infrastructure (such as additional termination points,) the MOU concludes three (3) months (90 days) post sign-off on the build and installation process which usually occurs two weeks after the project is complete and all clients are live";
$pdf->MultiCell(160, 6, $LongText, 0);

$pdf->AddPage('P');
$startY = 20;
$pdf->SetFont('Arial','B',10);
$pdf->SetXY(25, $startY);
$pdf->Cell(6, 6, "(b)", 0);
$pdf->SetXY(31, $startY);
$pdf->MultiCell(160, 6, "Cancellation Costs", 0);
$pdf->SetFont('Arial','',10);
$startY += 6;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Once the Body Corporate has signed the MOU with Company (its partners/contractors) this initiates the build and installation phase in order to render the services in terms of the MOU. Should the Body Corporate, for any reason, cancel the MOU at any stage during the installation, then the Body Corporate shall be liable to pay to Company for all costs incurred by Company up to that point. The Body Corporate will be supplied with a full breakdown of these costs in such an event and payment will be due in full no later than 30 days post invoicing";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 42;

$pdf->SetFont('Arial','B',10);
$pdf->SetXY(25, $startY);
$pdf->Cell(6, 6, "(c)", 0);
$pdf->SetXY(31, $startY);
$pdf->MultiCell(160, 6, "Destruction and Indemnities", 0);
$pdf->SetFont('Arial','',10);
$startY += 6;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "It is recorded that the cable strands or cable will not be owned by the customer and the customer shall not have any access to the duct systems in which the leased cable strands or cable are located, it being confirmed that Company or its authorised partners/subcontractors are the only parties entitled to such access";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 24;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Should cable strands or cables installed by Company (its partners/contractors) be destroyed or damaged to an extent which prevents the customer from having the beneficial use thereof, the customer shall, provided that the destruction or damage was not caused by the negligence and/or wilful acts or omissions on the part of Company (its partners/contractors), have no claim of any nature whatsoever against Company (its partners/contractors) as a result thereof, no matter how such destruction or damage was caused";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 36;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "If the total or partial destruction of cable strands or cables, installed by Company (its partners/contractors), is caused by any wilful act or omission of the Body Corporate or of any person for whose acts or omissions the Body Corporate is vicariously liable at law (residents of the complex, guests and contractors), the guilty party (residents, guests, contractors) will be held financially liable to Company for all damages suffered. ";
$LongText .= "In the event that the guilty party is not known and the damage has occurred on common property the HOA shall be liable to Company for all damages suffered as a result of and in connection with such total or partial destruction";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 48;
$pdf->SetFont('Arial','B',10);
$pdf->SetXY(25, $startY);
$pdf->Cell(6, 6, "(d)", 0);
$pdf->SetXY(31, $startY);
$pdf->MultiCell(160, 6, "MOU review process:", 0);
$pdf->SetFont('Arial','',10);
$startY += 6;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "This MOU is a living document which will have additional annexures attached once they have been agreed upon by both parties. These annexures will provide supplementary material that provides more detail on relevant matters, including such things as agreed work plans, milestones, timelines, budgetary matters (if required), minutes of meetings etc. These annexures will be submitted by Company to the Body Corporate for approval. On receiving the approval, Company will attach the Annexure to the MOU";
$pdf->MultiCell(160, 6, $LongText, 0);
$pdf->AddPage('P');
$startY = 20;
$pdf->SetFont('Arial','B',10);
$pdf->SetXY(25, $startY);
$pdf->Cell(6, 6, "(e)", 0);
$pdf->SetXY(31, $startY);
$pdf->MultiCell(160, 6, "Dispute resolution, including (or excluding) legal actions, negotiations, consultations, or executive actions:", 0);
$pdf->SetFont('Arial','',10);
$startY += 12;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Company undertakes to always inform the Body Corporate of any events that could potentially delay the build and installation process, and requests the same in return should the Body Corporate be aware of any reason why Company (or its partners/contractors) cannot, for example, be on site for a period of time which would delay the build and installation process";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 24;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "When experiencing a dispute, or if the Body Corporate has an additional request then the best route is always to first contact the Company representative via telephone or email in order to resolve the matter quickly and efficiently";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 18;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "It is in the best interests of both parties for any disputes to be resolved quickly. Should either Party fail to fulfil its expected responsibilities under the terms of this MOU, or fail to remedy a dispute which has been brought to their attention, the notice of breach must be submitted via registered post to the relevant party. Should the situation not be resolved within 7 (seven) business days of receipt of the written notice calling upon it to do so, then the other party will be entitled, but not obliged, to cancel the agreement inherent in this MOU with or without claiming damages, provided that such breach constitutes a material breach";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 48;
$pdf->SetFont('Arial','B',10);
$pdf->SetXY(25, $startY);
$pdf->Cell(6, 6, "(f)", 0);
$pdf->SetXY(31, $startY);
$pdf->MultiCell(160, 6, "Privacy provisions: ", 0);
$pdf->SetFont('Arial','',10);
$startY += 6;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Intio agrees not to share the personal details of any resident in " . $Complex['complexname'] . " without their express written permission.";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 12;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "The Body Corporate agrees not to share any of the proprietary information, processes and procedures used by Company without an authorised Company Director's express written permission";
$pdf->MultiCell(160, 6, $LongText, 0);

$pdf->AddPage('P');
$startY = 20;
$pdf->SetFont('Arial','B',12);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "Declaration of endorsement", 0, 0);
$pdf->SetFont('Arial','',10);
$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->Cell(175, 5, "I have read, understand and agree to the stipulations in this Memorandum of Understanding.", 0, 0);
$pdf->SetFont('Arial','B',10);
$startY += 15;
$pdf->SetXY(15, $startY);
$pdf->Cell(175, 5, "For the Body Corporate", 0, 0);
$pdf->SetFont('Arial','',10);

$pdf->SetFont('Arial','B',10);
$startY += 20;
$pdf->SetXY(15, $startY);
$pdf->Cell(175, 5, "For the Body Corporate", 0, 0);
$pdf->SetFont('Arial','',10);

$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->Cell(175, 5, "Signed this ____________ day of ______________________ 20_____ at _________________________", 0, 0);

$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->Cell(175, 5, "Authorised signatory name: _____________________________________________", 0, 0);

$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->Cell(175, 5, "Designation: _________________________________________________________", 0, 0);

$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->Cell(175, 5, "Signature: ___________________________________________________________", 0, 0);

$pdf->SetFont('Arial','B',10);
$startY += 20;
$pdf->SetXY(15, $startY);
$pdf->Cell(175, 5, "For Company (Pty) Ltd", 0, 0);
$pdf->SetFont('Arial','',10);

$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->Cell(175, 5, "Signed this ____________ day of ______________________ 20_____ at _________________________", 0, 0);

$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->Cell(175, 5, "Authorised signatory name: _____________________________________________", 0, 0);

$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->Cell(175, 5, "Designation: _________________________________________________________", 0, 0);

$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->Cell(175, 5, "Signature: ___________________________________________________________", 0, 0);

$FileName = str_replace(" ", "_", $Complex['complexname']) . "_MOU_" . date("Ymd") . ".pdf";
$pdf->Output($FileName, $OutPutType);
unset($pdf);
?>