<?php
session_start();
include("db.inc.php");
$POType = pebkac($_POST['POTypeID'], 1);
$OrderArr = $_POST['po_order'];
$PO_ID = createPOOrder($POType);
foreach($OrderArr AS $Key => $OrderID)
{
	addOrderToPO($PO_ID, $OrderID);
}
$Orders = getUnitOrders();
$PackageArr = getFibrePackages();
$VendorSpeeds = getPackageSpeeds();
$VendorONTs = getONTTypes();
$Suburbs = getSuburbs();
$POTypes = getPOTypes();
$SysUsers = getUsers();
foreach($Orders AS $UnitID => $OrderRec)
{
	$UnitIDList[] = $UnitID;
	$CustomerIDList[] = $OrderRec['customerid'];
}
$Customers = getCustomersByIDList(implode(",", $CustomerIDList));
$Units = getUnitsByIDList(implode(",", $UnitIDList));
foreach($Units AS $UnitID => $UnitRec)
{
	$ComplexIDList[] = $UnitRec['complexid'];
}
$Complexes = getComplexesByIDList(implode(",", $ComplexIDList));
require_once('PHPExcel.php');
$FileName = 'IRIS_' . date("Ymd") . '_PurchaseOrder_' . $PO_ID . '_' . $POTypes[$POType] . '.xlsx';
$styleThinBlackBorderOutline = array('borders' => array('outline' => array('style' => PHPExcel_Style_Border::BORDER_THIN, 'color' => array('argb' => 'FF000000'),),),);
$styleThickBrownBorderOutline = array('borders' => array('outline' => array('style' => PHPExcel_Style_Border::BORDER_THICK,	'color' => array('argb' => 'FF993300'),),),);
$styleThickBlackBorderOutline = array('borders' => array('outline' => array('style' => PHPExcel_Style_Border::BORDER_THICK,	'color' => array('argb' => 'FF000000'),),),);
$objPHPExcel = new PHPExcel();
$objPHPExcel->getProperties()->setCreator("IRIS");
$objPHPExcel->getProperties()->setLastModifiedBy("IRIS");
$objPHPExcel->getProperties()->setTitle("IRIS " . $POTypes[$POType] . " Purchase Order");
$objPHPExcel->getProperties()->setSubject("IRIS " . $POTypes[$POType] . " Purchase Order");
$objPHPExcel->getProperties()->setDescription($POTypes[$POType] . " Purchase Order. Generated by IRIS");
$objPHPExcel->setActiveSheetIndex(0);
$objPHPActiveSheet = $objPHPExcel->getActiveSheet();
$objPHPActiveSheet->setTitle($POTypes[$POType] . ' Purchase Order');
$ThisRow = 1;
$objPHPActiveSheet->setCellValue('A' . $ThisRow, 'PO Number');
$objPHPActiveSheet->setCellValue('B' . $ThisRow, $PO_ID);
$ThisRow++;
$objPHPActiveSheet->getStyle('A' . $ThisRow . ':O' . $ThisRow)->getFont()->setBold(true);
$objPHPActiveSheet->getStyle('A' . $ThisRow . ':O' . $ThisRow)->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);
$objPHPActiveSheet->getStyle('A' . $ThisRow . ':O' . $ThisRow)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
$objPHPActiveSheet->getColumnDimension('A')->setWidth('14');
$objPHPActiveSheet->getColumnDimension('B')->setWidth('16');
$objPHPActiveSheet->getColumnDimension('C')->setWidth('20');
$objPHPActiveSheet->getColumnDimension('D')->setWidth('15');
$objPHPActiveSheet->getColumnDimension('E')->setWidth('17');
$objPHPActiveSheet->getColumnDimension('F')->setWidth('30');
$objPHPActiveSheet->getColumnDimension('G')->setWidth('35');
$objPHPActiveSheet->getColumnDimension('H')->setWidth('13');
$objPHPActiveSheet->getColumnDimension('I')->setWidth('11');
$objPHPActiveSheet->getColumnDimension('J')->setWidth('8');
$objPHPActiveSheet->getColumnDimension('K')->setWidth('5');
$objPHPActiveSheet->getColumnDimension('L')->setWidth('11');
$objPHPActiveSheet->getColumnDimension('M')->setWidth('14');
$objPHPActiveSheet->getColumnDimension('N')->setWidth('10');
$objPHPActiveSheet->getColumnDimension('O')->setWidth('15');
$objPHPActiveSheet->getStyle('A' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('B' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('C' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('D' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('E' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('F' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('G' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('H' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('I' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('J' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('K' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('L' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('M' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('N' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->getStyle('O' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
$objPHPActiveSheet->setCellValue('A' . $ThisRow, 'Reseller/ISP');
$objPHPActiveSheet->setCellValue('B' . $ThisRow, 'Cluster');
$objPHPActiveSheet->setCellValue('C' . $ThisRow, 'Full Name');
$objPHPActiveSheet->setCellValue('D' . $ThisRow, 'House / Unit no.');	
$objPHPActiveSheet->setCellValue('E' . $ThisRow, 'Complex');
$objPHPActiveSheet->setCellValue('F' . $ThisRow, 'Address');
$objPHPActiveSheet->setCellValue('G' . $ThisRow, 'Email');
$objPHPActiveSheet->setCellValue('H' . $ThisRow, 'Phone');
$objPHPActiveSheet->setCellValue('I' . $ThisRow, 'Description');	
$objPHPActiveSheet->setCellValue('J' . $ThisRow, 'Package');
$objPHPActiveSheet->setCellValue('K' . $ThisRow, 'MRC');
$objPHPActiveSheet->setCellValue('L' . $ThisRow, 'ONT');
$objPHPActiveSheet->setCellValue('M' . $ThisRow, 'Contract period');
$objPHPActiveSheet->setCellValue('N' . $ThisRow, 'NRC (ONT)');
$objPHPActiveSheet->setCellValue('O' . $ThisRow, 'NRC');
// $objPHPActiveSheet->setCellValue('P' . $ThisRow, 'Installation Cost');
$ThisRow++;
foreach($Orders AS $UnitID => $OrderRec)
{
	foreach($OrderRec['orders'] AS $OrderID => $LineItem)
	{
		if(in_array($OrderID, $OrderArr))
		{
			$LineSpeed = $VendorSpeeds[$LineItem['speedid']];
			$CustomerID = $Units[$UnitID]['customerid'];
			$ComplexID = $Units[$UnitID]['complexid'];
			$objPHPActiveSheet->getStyle('A' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
			$objPHPActiveSheet->getStyle('B' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
			$objPHPActiveSheet->getStyle('C' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
			$objPHPActiveSheet->getStyle('D' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
			$objPHPActiveSheet->getStyle('E' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
			$objPHPActiveSheet->getStyle('F' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
			$objPHPActiveSheet->getStyle('G' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
			$objPHPActiveSheet->getStyle('H' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
			$objPHPActiveSheet->getStyle('I' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
			$objPHPActiveSheet->getStyle('J' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
			$objPHPActiveSheet->getStyle('K' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
			$objPHPActiveSheet->getStyle('L' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
			$objPHPActiveSheet->getStyle('M' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
			$objPHPActiveSheet->getStyle('N' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
			$objPHPActiveSheet->getStyle('O' . $ThisRow)->applyFromArray($styleThinBlackBorderOutline);
			$objPHPActiveSheet->setCellValue('A' . $ThisRow, 'Company');
			if(isset($Suburbs[$Complexes[$ComplexID]['suburbid']]))
				$objPHPActiveSheet->setCellValue('B' . $ThisRow, $Suburbs[$Complexes[$ComplexID]['suburbid']]['suburbname']);
			// $objPHPActiveSheet->setCellValue('B' . $ThisRow, $Suburbs[$Complexes[$ComplexID]['suburbid']]['suburbname']);
			$objPHPActiveSheet->setCellValue('C' . $ThisRow, $Customers[$CustomerID]['customername'] . " " . $Customers[$CustomerID]['customersurname']);
			$objPHPActiveSheet->setCellValue('D' . $ThisRow, $Units[$UnitID]['unitnumber']);	
			$objPHPActiveSheet->setCellValue('E' . $ThisRow, $Complexes[$ComplexID]['complexname']);
			$objPHPActiveSheet->setCellValue('F' . $ThisRow, $Complexes[$ComplexID]['streetaddress1'] . " " . $Complexes[$ComplexID]['streetaddress2'] . " " . $Complexes[$ComplexID]['streetaddress3'] . " " . $Complexes[$ComplexID]['streetaddress4'] . " " . $Complexes[$ComplexID]['streetaddress5']);
			$objPHPActiveSheet->setCellValue('G' . $ThisRow, $Customers[$CustomerID]['email1']);
			$objPHPActiveSheet->setCellValue('H' . $ThisRow, $Customers[$CustomerID]['cell1']);
			$objPHPActiveSheet->setCellValue('I' . $ThisRow, $POTypes[$POType]);	
			$objPHPActiveSheet->setCellValue('J' . $ThisRow, $LineSpeed);
			$objPHPActiveSheet->setCellValue('K' . $ThisRow, $PackageArr[$LineItem['packageid']]['costprice']);
			$objPHPActiveSheet->setCellValue('L' . $ThisRow, $VendorONTs[$PackageArr[$LineItem['packageid']]['ontid']]['ontname']);
			$objPHPActiveSheet->setCellValue('M' . $ThisRow, $LineItem['termnum']);
			$objPHPActiveSheet->setCellValue('N' . $ThisRow, $PackageArr[$LineItem['packageid']]['networkontcost']);
			$objPHPActiveSheet->setCellValue('O' . $ThisRow, $PackageArr[$LineItem['packageid']]['networkinstallcost']);
			// $objPHPActiveSheet->setCellValue('P' . $ThisRow, $PackageArr[$LineItem['packageid']]['networkconnectcost']);
			$ThisRow++;
			$SaveArr = array('orderstatus' => 2);
			updateUnitPackage($OrderID, $SaveArr);
		}
	}
}
$SigImg = 'images/jkssignature.png';
if(file_exists($SigImg))
{
	$ThisRow += 2;
	$objDrawing = new PHPExcel_Worksheet_Drawing();
	$objDrawing->setName('Signature');
	$objDrawing->setDescription('Signature');
	$objDrawing->setPath($SigImg);
	$newSize = resizeImage($objDrawing->getWidth(), $objDrawing->getHeight(), 150, 75);
	$objDrawing->setWidth($newSize['width']);
	$objDrawing->setHeight($newSize['height']);
	$objDrawing->setCoordinates('B' . $ThisRow);
	$objDrawing->setWorksheet($objPHPActiveSheet);
}
$LogoImg = 'images/logo 251x58.png';
if(file_exists($LogoImg))
{
	$ThisRow++;
	$objDrawing = new PHPExcel_Worksheet_Drawing();
	$objDrawing->setName('Signature');
	$objDrawing->setDescription('Signature');
	$objDrawing->setPath($LogoImg);
	// $newSize = resizeImage($objDrawing->getWidth(), $objDrawing->getHeight(), 300, 140);
	// $objDrawing->setWidth($newSize['width']);
	// $objDrawing->setHeight($newSize['height']);
	$objDrawing->setCoordinates('C' . $ThisRow);
	$objDrawing->setWorksheet($objPHPActiveSheet);
}
$ThisRow += 3;
$objPHPActiveSheet->setCellValue('A' . $ThisRow, 'Approved:');
$objPHPActiveSheet->setCellValue('B' . $ThisRow, date("d M Y"));
$ThisRow++;
$objPHPActiveSheet->setCellValue('A' . $ThisRow, 'Approved by:');
$objPHPActiveSheet->setCellValue('B' . $ThisRow, $SysUsers[$_SESSION['userid']]['firstname'] . " " . $SysUsers[$_SESSION['userid']]['surname']);


$objPHPExcel->setActiveSheetIndex(0);
// Redirect output to a client’s web browser (Excel2007)
header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="' . $FileName . '"');
header('Cache-Control: max-age=0');
// If you're serving to IE 9, then the following may be needed
header('Cache-Control: max-age=1');
// If you're serving to IE over SSL, then the following may be needed
header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
header ('Pragma: public'); // HTTP/1.0
$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
$objWriter->save('php://output');
$objPHPExcel->disconnectWorksheets(); // Disconnect before you unset to properly clear the memory
unset($objPHPExcel);
unset($objWriter);
?>