<?php
include("db.inc.php");
define('FPDF_FONTPATH','font/');
require('fpdf.php');

$ComplexID = pebkac($_GET['cid'], 5);
$Complex = getComplexByID($ComplexID);
$OutPutType = 'I';
$startY = 35;
class PDF extends FPDF
{
	function Header()
	{
		global $startY;
		global $Complex;
		if($this->page > 1)
		{
			$this->SetFont('Arial','',10);
			$this->SetXY(190, 10);
			$this->Cell(10, 5, $this->page, 0, 0);
		}
	}

	function Footer()
	{
		global $Complex;
		if($this->page > 1)
		{
			$IniLogo = "images/logo 251x58.png";
			$this->Image($IniLogo, 160, 280, 30);
			$this->SetXY(15, 282);
			$this->SetTextColor(187, 187, 187);
			$this->Cell(100, 5, "Introductory proposal: " . $Complex['complexname'], 0, 0);
			$this->SetTextColor(0, 0, 0);
		}
	}
}
$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage('P');
$pdf->SetFont('Arial','B',18);
$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "Introductory proposal", 0, 0, 'C');
$pdf->SetFont('Arial','',14);
$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "for home fibre installation", 0, 0, 'C');
$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "and solutions provided by", 0, 0, 'C');
$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->SetFont('Arial','B',18);
$pdf->Cell(180, 6, "Company (Pty) Ltd", 0, 0, 'C');
$startY += 10;
$pdf->SetXY(15, $startY);
$pdf->SetFont('Arial','',14);
$pdf->Cell(180, 6, "the body corporate/home owners' association of", 0, 0, 'C');
$startY += 10;
$pdf->SetFont('Arial','B',18);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, $Complex['complexname'], 0, 0, 'C');
$IniLogo = "images/logo 658x150.png";
$startY += 50;
$pdf->Image($IniLogo, 65, $startY, 80);
$pdf->AddPage('P');
$startY = 35;
$pdf->SetFont('Arial','B',16);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 5, 'Contents', 0, 0);
$pdf->SetFont('Arial','',10);
$startY += 6;
$pdf->SetXY(20, $startY);
$pdf->Cell(160, 5, "Contents....................................................................................................................................................", 0, 0);
$pdf->Cell(10, 5, '2', 0, 0);
$startY += 6;
$pdf->SetXY(20, $startY);
$pdf->Cell(160, 5, "Overview....................................................................................................................................................", 0, 0);
$pdf->Cell(10, 5, '3', 0, 0);
$startY += 6;
$pdf->SetXY(20, $startY);
$pdf->Cell(160, 5, "About Us.................................................................................................................................................", 0, 0);
$pdf->Cell(10, 5, '4', 0, 0);
$startY += 6;
$pdf->SetXY(20, $startY);
$pdf->Cell(160, 5, "How we do business..................................................................................................................................", 0, 0);
$pdf->Cell(10, 5, '4', 0, 0);
$startY += 6;
$pdf->SetXY(20, $startY);
$pdf->Cell(160, 5, "Our Process...............................................................................................................................................", 0, 0);
$pdf->Cell(10, 5, '5', 0, 0);
$startY += 6;
$pdf->SetXY(20, $startY);
$pdf->Cell(160, 5, "Annexure A: Internal Marketing Plan.........................................................................................................", 0, 0);
$pdf->Cell(10, 5, '7', 0, 0);
$startY += 6;
$pdf->SetXY(20, $startY);
$pdf->Cell(160, 5, "Annexure B: Company Fibre Packages............................................................................................................", 0, 0);
$pdf->Cell(10, 5, '3', 0, 0);
$startY += 6;
$pdf->SetXY(20, $startY);
$pdf->Cell(160, 5, "Annexure C: Useful definitions of fibre-related terminology.......................................................................", 0, 0);
$pdf->Cell(10, 5, '3', 0, 0);
$startY += 6;
$pdf->SetXY(20, $startY);
$pdf->Cell(160, 5, "Annexure D: Letter of Engagement and Permission.................................................................................", 0, 0);
$pdf->Cell(10, 5, '3', 0, 0);
$startY += 6;
$pdf->SetXY(20, $startY);
$pdf->Cell(160, 5, "Annexure D: Memorandum of Understanding...........................................................................................", 0, 0);
$pdf->Cell(10, 5, '3', 0, 0);
$pdf->AddPage('P');
$startY = 20;
$pdf->SetFont('Arial','B',16);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "Overview", 0, 0);
$pdf->SetFont('Arial','',10);
$startY += 10;
$pdf->SetXY(15, $startY);
$LongText = "The purpose of this document is to introduce you to Company (Pty) Ltd (Company), and its partners, and to explain how we can assist you in bringing fibre into the homes of all your residents with the least amount of stress. It will clearly lay out our processes so you have a clear understanding of it and so you know what to expect from the build and installation.";
$pdf->MultiCell(180, 6, $LongText, 0);
$startY += 30;
$pdf->SetFont('Arial','B',16);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "About Company", 0, 0);
$pdf->SetFont('Arial','',10);
$startY += 10;

$LongText = "Company was established after its directors experienced the fibre installation process from a customer perspective. It was clear there was a need in the market for a more customer-centric, and efficient approach to fibre installations into residential complexes and estates. Issues like poor communication, long, undefined build periods, inexperienced and unreliable sub-contractors and security threats, caused headaches for body corporates and residents alike.";
$pdf->SetXY(15, $startY);
$pdf->MultiCell(180, 6, $LongText, 0);
$startY += 32;
$LongText = "The directors created Company (Pty) Ltd to specifically address these issues and they place the customer at the forefront of everything they do.";
$pdf->SetXY(15, $startY);
$pdf->MultiCell(180, 6, $LongText, 0);
$startY += 14;
$LongText = "Company provides a complete end-to-end fibre solution, from the physical fibre backbone build, to the provision of ISP packages and technical support to individual residents. None of the The build and installation process is professionally managed by our experienced partner, Initeccontracted out  , while Company manages the as the company has its own build and installation teams, technical support experts and internet connectivity packages. This greatly reduces any security threats on your premises as our employees are clearly identifiable and are supervised onsite at all times. We work with your onsite security to ensure they know who will be coming in and out of the premises and when they will do so.";
$pdf->SetXY(15, $startY);
$pdf->MultiCell(180, 6, $LongText, 0);
$startY += 44;
$LongText = "To ensure effective communication and swift resolution of any issues which may arise, the management team assigns a single point of contact between the body corporate, the residents and Company. Company uses an online proprietary customer relations needs and support system (IRIS) that allows all residents to:";
$pdf->SetXY(15, $startY);
$pdf->MultiCell(180, 6, $LongText, 0);
$startY += 18;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "track the build process";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 6;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "book appointments which are convenient to them to allow Company's installation team access to their properties";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 12;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "log queries or issues which can be efficiently tracked and timeously resolved";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 6;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "request and receive marketing material around internet connectivity packages";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 6;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "calculate which internet connectivity package best suits their specific requirements";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 8;
$LongText = "It is easy to become overwhelmed by the myriad of internet connectivity packages available on the market today. We've simplified the process for our customers. Our five packages all offer super-fast, uncapped, low-latency, and symmetrical upload and download speeds. They are available on month-to-month or twelve-month contracts.";
$pdf->SetXY(15, $startY);
$pdf->MultiCell(180, 6, $LongText, 0);
$pdf->AddPage('P');
$startY = 20;
$pdf->SetFont('Arial','B',16);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "How we do business", 0, 0);
$pdf->SetFont('Arial','',10);
$startY += 10;

$LongText = "Company takes the frustration of residential complex and estate fibre builds and installation. We work closely with you and your body corporate or home owners association, to ensure that:";
$pdf->SetXY(15, $startY);
$pdf->MultiCell(180, 6, $LongText, 0);
$startY += 18;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Every resident fully understands and knows what to expect during each phase of the build and installation process";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 12;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Every resident  has clear timelines for each stage of the process";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 6;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Every resident  has a dedicated contact point for all questions or issue which may arise";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 6;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Your complex's site plan is correctly surveyed, completed and approved by your body corporate or home owners association prior to the build phase. Where possible existing infrastructure will be used";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 12;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "An internal marketing strategy is discussed and approved by the trustees so that each resident receives regular updates on the build process and available fibre internet access package options";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 12;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "All interested and affected residents have access to our web-based proprietary programme IRIS";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 12;
$pdf->SetXY(35, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(40, $startY);
$LongText = "This programme allows for convenient scheduling of access to residents' homes so our installation teams can install the fibre termination points and routers for those customers who have signed up for a package";
$pdf->MultiCell(150, 6, $LongText, 0);
$startY += 18;
$pdf->SetXY(35, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(40, $startY);
$LongText = "It also gives residents access to Company services and support, making it easy to track progress, learn more and log any problems they might experience so they can be quickly and easily resolved";
$pdf->MultiCell(150, 6, $LongText, 0);
$startY += 18;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Every resident receives ongoing support from our support team with the backing of technically proficient experts";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 30;
$pdf->SetFont('Arial','B',16);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "Our Process", 0, 0);
$pdf->SetFont('Arial','',10);
$startY += 10;

$pdf->SetXY(35, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(40, $startY);
$LongText = "When you engage Company with the prospect of installing fibre in your complex, we will conduct a feasibility study to ensure there is a minimum uptake of at least 30% of the residents. Should the minimum uptake be confirmed, and the letter of engagement and permission, as well as the memorandum of agreement be signed by the authorised representative of the body corporate, then there will be no fee for the installation of the complex fibre backbone and the termination points into the residences for the duration of the installation project.";
$pdf->MultiCell(150, 6, $LongText, 0);
$startY += 36;
$pdf->SetXY(35, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(40, $startY);
$LongText = "In order to ensure a return on Company's investment in the complex, there is the requirement of a three month period of exclusive service and marketing rights for fibre connectivity within the complex. Once this period is completed, the provided Network is an open access network which means other service providers that are registered on the Network can offer their services to the residents. The Company team will work closely with the Body Corporate to ensure that the marketing plan is suitable and adheres to the rules of the complex.";
$pdf->MultiCell(150, 6, $LongText, 0);
$pdf->AddPage('P');
$startY = 20;
$pdf->SetFont('Arial','B',12);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "Phase 1: Planning and Technical Phase", 0, 0);
$pdf->SetFont('Arial','',10);
$startY += 8;

$pdf->SetXY(15, $startY);
$LongText = "Once a viable uptake is confirmed, then the first phase of the project is launched. This is the planning and technical phase during which an onsite survey is conducted that will determine the best way to install the fibre infrastructure into your complex. It includes an inspection of existing infrastructure (such as manholes) and installation requirements based upon the layout of the complex, such as trenching (digging to lay conduits across internal roadways), and allows us to identify the materials needed to complete the project.";
$pdf->MultiCell(180, 6, $LongText, 0);
$startY += 34;
$pdf->SetXY(15, $startY);
$LongText = "A site plan is produced that will indicated where the fibre backbone will be laid and where it will enter the individual units. This site plan is presented to the body corporate for comment and approval. Once the body corporate has approved the site plan and any changes that may be required, the projected will be scheduled and the body corporate and residents will be informed of the estimated timeline and kick-off date. (The average installation time for medium-size complexes has thus far been 6 - 8 weeks.)";
$pdf->MultiCell(180, 6, $LongText, 0);
$startY += 34;
$pdf->SetXY(15, $startY);
$LongText = "Company will also provide an agreed number of connection points for security cameras should the Body Corporate have such a requirement. There will be no charge for these points and the locations of these points will be set during this planning phase. The cost of the cameras and other extra hardware however, will be for the Body Corporate's account.";
$pdf->MultiCell(180, 6, $LongText, 0);
$startY += 28;
$pdf->SetFont('Arial','B',12);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "Phase 2: Build and installation phase", 0, 0);
$pdf->SetFont('Arial','',10);
$startY += 8;
$LongText = "The second phase is the physical build and installation. This is when our installation teams start their work onsite. They will connect and lay a fibre backbone from the fibre cables installed on the pavements outside your complex, bringing it into your complex. For those residents wishing to sign up for one of our fibre connectivity packages, fibre termination points (internal connection points) are then also installed in their units. Individual access to homes for residents who have requested the installation of a fibre termination point and router will be facilitated through residents scheduling appointments that are convenient for them on IRIS. Should a team not be able to be present at that time for any reason, the resident and body corporate representative will be timeously notified to cause the least amount of inconvenience for them. At any time, questions can be directed to either your complex's Company contact or the on-site project manager.";
$pdf->SetXY(15, $startY);
$pdf->MultiCell(180, 6, $LongText, 0);
$startY += 58;

$pdf->SetFont('Arial','B',12);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "Risk Factors", 0, 0);
$pdf->SetFont('Arial','',10);
$startY += 8;
$pdf->SetXY(15, $startY);
$LongText = "It is important to note that sometimes unforeseen factors could affect the build and installation timeline. Examples of these include among others:";
$pdf->MultiCell(180, 6, $LongText, 0);
$startY += 12;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "A delay in council approvals, wayleaves (permission to access the site) or body corporate approvals";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 6;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "The condition of existing infrastructure – should the existing infrastructure be found to be very deteriorated or inadequate, new infrastructure will need to be built";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 12;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Difficulty in gaining access to residences for the installation of termination points or additional residents signing up during the installation phase which require additional termination points to be installed ";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 18;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Inclement weather / environmental factors can cause delays. For reasons of health and safety, our teams are not permitted to work in bad weather. Heavy rains or other severe weather pose a temporary hazard to the build/infrastructure and our people";
$pdf->MultiCell(160, 6, $LongText, 0);
$startY += 18;
$pdf->SetXY(15, $startY);
$LongText = "Should any of these factors arise, we will communicate them timeously to Body Corporate and residents.";
$pdf->MultiCell(180, 6, $LongText, 0);

$pdf->AddPage('P');
$startY = 20;
$pdf->SetFont('Arial','B',18);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "Annexure A: Useful definitions of fibre-related terminology", 0, 0);
$pdf->SetFont('Arial','',10);
$startY += 10;
$pdf->SetXY(15, $startY);
$LongText = "While we haven't used all this terminology in our introductory proposal, you've likely heard these terms during your research phase so we thought we would include some useful definitions for you";
$pdf->MultiCell(180, 6, $LongText, 0);
$startY += 12;
$pdf->SetXY(15, $startY);


$startY += 6;
$pdf->SetFont('Arial','B',8);
$pdf->SetXY(15, $startY);
$pdf->Cell(80, 5, "BANDWIDTH:", 0, 0);
$startY += 6;
$pdf->SetFont('Arial','',8);
$pdf->SetXY(15, $startY);
$LongText = "'Bandwidth' describes the rate at which data can be transferred to your computer from a website or internet service within a specific time and is measured in bits per second.";
$pdf->MultiCell(180, 5, $LongText, 0);
$startY += 12;

$pdf->SetFont('Arial','B',8);
$pdf->SetXY(15, $startY);
$pdf->Cell(80, 5, "FIBRE OPTICS:", 0, 0);
$startY += 6;
$pdf->SetFont('Arial','',8);
$pdf->SetXY(15, $startY);
$LongText = "A fibre optic cable consists of a bundle of glass threads, each of which is capable of transmitting messages modulated onto light waves. Fibre optics has several advantages over traditional metal communications lines: Fibre optic cables have a much greater bandwidth than metal cables.";
$pdf->MultiCell(180, 5, $LongText, 0);
$startY += 18;

$pdf->SetFont('Arial','B',8);
$pdf->SetXY(15, $startY);
$pdf->Cell(80, 5, "ISP:", 0, 0);
$startY += 6;
$pdf->SetFont('Arial','',8);
$pdf->SetXY(15, $startY);
$LongText = "An Internet Service Provider (ISP) is a company that provides you with access to the Internet for a fee. The ways to connect to an ISP are by using a phone line (dial-up), broadband connection (cable or DSL) or a Fibre Optic Line.";
$pdf->MultiCell(180, 5, $LongText, 0);
$startY += 12;

$pdf->SetFont('Arial','B',8);
$pdf->SetXY(15, $startY);
$pdf->Cell(80, 5, "MBPS:", 0, 0);
$startY += 6;
$pdf->SetFont('Arial','',8);
$pdf->SetXY(15, $startY);
$LongText = "This is your Internet speed of data or content which travels from the World Wide Web to your home computer, tablet, or smartphone. The speed of this data is measured in megabits per second (MBPS).";
$pdf->MultiCell(180, 5, $LongText, 0);
$startY += 12;

$pdf->SetFont('Arial','B',8);
$pdf->SetXY(15, $startY);
$pdf->Cell(80, 5, "OPEN ACCESS NETWORK:", 0, 0);
$startY += 6;
$pdf->SetFont('Arial','',8);
$pdf->SetXY(15, $startY);
$LongText = "A fibre network built by an operator in a specific area that allows multiple ISP's (Internet Service Providers) or SP (Service Providers) to sell fibre services over its network. An open access network removes the need for multiple operators to build duplicate network infrastructure in the same area and opens up the market to competition by allowing various ISP's to provide competitively priced fibre service to the market.";
$pdf->MultiCell(180, 5, $LongText, 0);
$startY += 18;

$pdf->SetFont('Arial','B',8);
$pdf->SetXY(15, $startY);
$pdf->Cell(80, 5, "ONT:", 0, 0);
$startY += 6;
$pdf->SetFont('Arial','',8);
$pdf->SetXY(15, $startY);
$LongText = "ONT stands for Optical Network Terminal. The ONT (also called the modem) connects to the Termination Point (TP) with an optical fibre cable. It translates light signals from the fibre optic line from your TP into electronic signals that your router can read. (The ONT supplied by Company has a built in Router and Wi-Fi functionalities)";
$pdf->MultiCell(180, 5, $LongText, 0);
$startY += 18;

$pdf->SetFont('Arial','B',8);
$pdf->SetXY(15, $startY);
$pdf->Cell(80, 5, "TP:", 0, 0);
$startY += 6;
$pdf->SetFont('Arial','',8);
$pdf->SetXY(15, $startY);
$LongText = "A TP is the Termination point, which is the physical wall jack installed in your home. It is where the actual fibre optic cable that we install ends.";
$pdf->MultiCell(180, 5, $LongText, 0);
$startY += 6;

$pdf->SetFont('Arial','B',8);
$pdf->SetXY(15, $startY);
$pdf->Cell(80, 5, "SMART HOME:", 0, 0);
$startY += 6;
$pdf->SetFont('Arial','',8);
$pdf->SetXY(15, $startY);
$LongText = "A smart home is one where a home owner through an internet connected device, like a smart phone or PC, can access and control various functionalities within their home; such as:";
$pdf->MultiCell(180, 5, $LongText, 0);
$startY += 10;

$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Security cameras and alarms";
$pdf->MultiCell(160, 5, $LongText, 0);
$startY += 5;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Lights";
$pdf->MultiCell(160, 5, $LongText, 0);
$startY += 5;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Air conditioners";
$pdf->MultiCell(160, 5, $LongText, 0);
$startY += 5;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Lock/unlock doors";
$pdf->MultiCell(160, 5, $LongText, 0);
$startY += 5;
$pdf->SetXY(30, $startY);
$pdf->Cell(3, 6, chr(127), 0);
$pdf->SetXY(33, $startY);
$LongText = "Pool pumps and garden irrigation systems...";
$pdf->MultiCell(160, 5, $LongText, 0);
$startY += 8;

$pdf->SetFont('Arial','B',8);
$pdf->SetXY(15, $startY);
$pdf->Cell(80, 5, "VOIP:", 0, 0);
$startY += 6;
$pdf->SetFont('Arial','',8);
$pdf->SetXY(15, $startY);
$LongText = "A VoIP phone is a telephone set designed specifically for use in a voice over IP (VOIP) system by converting standard telephone audio into a digital format that can be transmitted over the Internet, and by converting incoming digital phone signals from the Internet to standard telephone audio.";
$pdf->MultiCell(180, 5, $LongText, 0);

$pdf->AddPage('P');
$startY = 20;
$pdf->SetFont('Arial','B',18);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "Annexure B: Fibre Packages", 0, 0);

$IniLogo = "images/pricing953x653.png";
$pdf->Image($IniLogo, 19, 30, 170);

$pdf->AddPage('P');
$startY = 20;
$pdf->SetFont('Arial','B',18);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "Annexure C: Internal Marketing Plan", 0, 0);
$startY += 20;
// $pdf->AddPage('P');
// $startY = 20;
$pdf->SetFont('Arial','B',18);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "Annexure D: Letter of Engagement and Permission", 0, 0);
$startY += 20;
// $pdf->AddPage('P');
// $startY = 20;
$pdf->SetFont('Arial','B',18);
$pdf->SetXY(15, $startY);
$pdf->Cell(180, 6, "Annexure E: Memorandum of Understanding", 0, 0);

$FileName = str_replace(" ", "_", $Complex['complexname']) . "_Proposal_" . date("Ymd") . ".pdf";
$pdf->Output($FileName, $OutPutType);
unset($pdf);
?>